### ISSUE TITLE
NextJS build fails because of react-merge-refs

### ISSUE THREAD

**Issue by floriaaan** [creativetimofficial/material-tailwind#177]
```bash
> Build error occurred
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/react-merge-refs/dist/index.mjs not supported.
Instead change the require of /home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/react-merge-refs/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/@material-tailwind/react/components/Dialog/index.js:1:695)
    at Object.<anonymous> (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/@material-tailwind/react/index.js:1:504)
    at Object.4715 (/home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/pages/auth/login.js:207:18)
    at __webpack_require__ (/home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/webpack-runtime.js:25:[42](https://github.com/floriaaan/meet-at-cesi/runs/7578053972?check_suite_focus=true#step:5:43))
    at /home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/pages/auth/login.js:18:82
    at Function.__webpack_require__.a (/home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/webpack-runtime.js:103:13)
    at Object.2491 (/home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/pages/auth/login.js:11:21)
    at __webpack_require__ (/home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/pages/auth/login.js:378:39)
    at /home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/pages/auth/login.js:379:78
    at Function.__webpack_require__.X (/home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/webpack-runtime.js:190:21)
    at /home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/pages/auth/login.js:379:[47](https://github.com/floriaaan/meet-at-cesi/runs/7578053972?check_suite_focus=true#step:5:48)
    at Object.<anonymous> (/home/runner/work/meet-at-cesi/meet-at-cesi/.next/server/pages/auth/login.js:382:3)
    at Object.requirePage (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/next/dist/server/require.js:[48](https://github.com/floriaaan/meet-at-cesi/runs/7578053972?check_suite_focus=true#step:5:49):12)
    at Object.loadComponents (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/next/dist/server/load-components.js:58:23)
    at /home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/next/dist/build/utils.js:584:[52](https://github.com/floriaaan/meet-at-cesi/runs/7578053972?check_suite_focus=true#step:5:53)
    at Span.traceAsyncFn (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/next/dist/trace/trace.js:79:26)
    at Object.isPageStatic (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/next/dist/build/utils.js:580:29)
    at execFunction (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2826)
    at execHelper (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2484)
    at execMethod (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2[57](https://github.com/floriaaan/meet-at-cesi/runs/7578053972?check_suite_focus=true#step:5:58)2)
    at process.messageListener (/home/runner/work/meet-at-cesi/meet-at-cesi/node_modules/next/dist/compiled/jest-worker/processChild.js:1:1282)
    at process.emit (node:events:527:28) {
  type: 'Error',
  code: 'ERR_REQUIRE_ESM'
}
```

I don't even use Dialog component.

Node version: 16.14.2

package.json
```json
"dependencies": {
    "@headlessui/react": "^1.6.4",
    "@heroicons/react": "^1.0.6",
    "@material-tailwind/react": "^1.1.0",
    "@next-auth/prisma-adapter": "^1.0.3",
    "@prisma/client": "^3.15.2",
    "@supabase/supabase-js": "^1.35.3",
    "classnames": "^2.3.1",
    "formik": "^2.2.9",
    "framer-motion": "^6.5.1",
    "next": "12.1.6",
    "next-auth": "^4.5.0",
    "next-pwa": "^5.5.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "yup": "^0.32.11"
  }
```

**Comment by mattia-lau** [comment]
same issue. @timcreative 

react-merge-refs ESM only, is that able to copy the core code as lib?
```tsx
export function mergeRefs<T = any>(
  refs: Array<React.MutableRefObject<T> | React.LegacyRef<T>>
): React.RefCallback<T> {
  return (value) => {
    refs.forEach((ref) => {
      if (typeof ref === "function") {
        ref(value);
      } else if (ref != null) {
        (ref as React.MutableRefObject<T | null>).current = value;
      }
    });
  };
}
```

**Comment by system32uwu** [comment]
You can probably fix it using [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules). Note that the next.js version must be 12.1.6 or lower, last time I tried with 12.2 it broke.

**Comment by mattia-lau** [comment]
> You can probably fix it using [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules). Note that the next.js version must be 12.1.6 or lower, last time I tried with 12.2 it broke.

any sample code for next.config.js? i also tried that. but seems not working.

**Comment by system32uwu** [comment]
> > You can probably fix it using [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules). Note that the next.js version must be 12.1.6 or lower, last time I tried with 12.2 it broke.
> 
> any sample code for next.config.js? i also tried that. but seems not working.

Just tried and it's not working even with that plugin, nor with esmExternals. This is a common next.js [issue](https://github.com/vercel/next.js/discussions/27876) though.

**Comment by sajadevo** [comment]
Hi guys,

I'm going to test it today and try to find a workaround for this issue.

Cheers,
Sajad

**Comment by bamousa-mariem** [comment]
Hi everyone ,
Did you fix this issue ?

**Comment by sajadevo** [comment]
Hi guys,

This issue is fixed on the latest version please update the package: `npm i @material-tailwind/react@v1.2.0`.

Cheers,
Sajad
