### ISSUE TITLE
menu in input tag with onChange issue Menu>MenuList>li>input

### ISSUE THREAD

**Issue by Md-Anamul-Haque** [creativetimofficial/material-tailwind#288]
floating-ui.react.umd.js:3284 Uncaught TypeError: text.toLocaleLowerCase is not a function
    at floating-ui.react.umd.js:3284:154
    at Array.find (<anonymous>)
    at onKeyDown (floating-ui.react.umd.js:3284:111)
    at floating-ui.react.umd.js:3587:87
    at Array.forEach (<anonymous>)
    at acc.<computed> (floating-ui.react.umd.js:3587:73)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
(anonymous) @ floating-ui.react.umd.js:3284
onKeyDown @ floating-ui.react.umd.js:3284
(anonymous) @ floating-ui.react.umd.js:3587
acc.<computed> @ floating-ui.react.umd.js:3587
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
react-dom.development.js:4312 Uncaught TypeError: text.toLocaleLowerCase is not a function
    at floating-ui.react.umd.js:3284:154
    at Array.find (<anonymous>)
    at onKeyDown (floating-ui.react.umd.js:3284:111)
    at floating-ui.react.umd.js:3587:87
    at Array.forEach (<anonymous>)
    at acc.<computed> (floating-ui.react.umd.js:3587:73)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
(anonymous) @ floating-ui.react.umd.js:3284
onKeyDown @ floating-ui.react.umd.js:3284
(anonymous) @ floating-ui.react.umd.js:3587
acc.<computed> @ floating-ui.react.umd.js:3587
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430

**Comment by sajadevo** [comment]
@Md-Anamul-Haque 

This issue has been fixed on v1.4.0 please update to the latest version.

Cheers,
Sajad
