### ISSUE TITLE
Timeline component is broken

### ISSUE THREAD

**Issue by notlega** [creativetimofficial/material-tailwind#356]
Currently I'm working on an Astro website and the timeline component keeps throwing the same error no matter what I do.

## Dependencies

```json
"dependencies": {
    "@astrojs/markdoc": "^0.3.2",
    "@astrojs/react": "^2.2.1",
    "@astrojs/tailwind": "^3.1.3",
    "@heroicons/react": "^2.0.18",
    "@material-tailwind/react": "^2.0.1",
    "@tailwindcss/typography": "^0.5.9",
    "astro": "^2.6.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tailwindcss": "^3.0.24"
  },
```

## Code Snippet

```tsx
import {
  Timeline,
  TimelineItem,
  TimelineConnector,
  TimelineHeader,
  TimelineIcon,
  TimelineBody,
} from '@material-tailwind/react';

interface Props {
  title: string;
  date: string;
  description: string;
}

const TimelineComponent = ({ timelineArray }: { timelineArray: Props[] }) =>
  timelineArray.map((timeline) => (
    <Timeline>
      <TimelineItem color="blue" className="rounded-lg shadow-lg bg-white">
        <TimelineConnector />
        <TimelineHeader>
          <TimelineIcon />
          <div className="flex flex-col gap-1">
            <h6 className="font-semibold">{timeline.title}</h6>
            <p className="text-sm text-gray-500">{timeline.date}</p>
          </div>
        </TimelineHeader>
        <TimelineBody>
          <p className="text-sm text-gray-500">{timeline.description}</p>
        </TimelineBody>
      </TimelineItem>
    </Timeline>
  ));

export default TimelineComponent;
```

## Stacktrace

```
Error: useTimelineItemContext() must be used within a TimelineItem. It happens when you use TimelineIcon, TimelineConnector or TimelineBody components outside the TimelineItem component.
    at useTimelineItem (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\@material-tailwind+react@2.0.1_react-dom@18.2.0_react@18.2.0\node_modules\@material-tailwind\react\components\Timeline\TimelineItem.js:1:3255)
    at C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\@material-tailwind+react@2.0.1_react-dom@18.2.0_react@18.2.0\node_modules\@material-tailwind\react\components\Timeline\TimelineConnector.js:1:3422
    at renderWithHooks (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5662:16)
    at renderForwardRef (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5846:18)
    at renderElement (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6009:11)
    at renderNodeDestructiveImpl (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6080:14)
    at renderNode (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6263:12)
    at renderChildrenArray (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6215:7)
    at renderNodeDestructiveImpl (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6145:7)
    at renderNodeDestructive (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6080:14)
    at renderNode (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6263:12)
    at renderHostElement (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5646:3)
    at renderElement (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5956:5)
    at renderNodeDestructiveImpl (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6080:14)
    at renderForwardRef (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5863:5)
    at renderElement (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6009:11)
    at renderNodeDestructiveImpl (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6080:14)
    at renderNode (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6263:12)
    at renderChildrenArray (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6215:7)
    at renderNodeDestructiveImpl (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6145:7)
    at renderNodeDestructive (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6080:14)
    at renderIndeterminateComponent (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5789:7)
    at renderElement (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:5950:7)
    at renderNodeDestructiveImpl (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6108:11)
    at renderNodeDestructive (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6080:14)
    at retryTask (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6532:5)
    at performWork (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6580:7)
    at C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6904:12
    at scheduleWork (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:78:3)
    at startWork (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:6903:3)
    at renderToNodeStreamImpl (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:7048:3)
    at Object.renderToStaticNodeStream (C:\Users\camak\Documents\notlega.github.io\node_modules\.pnpm\react-dom@18.2.0_react@18.2.0\node_modules\react-dom\cjs\react-dom-server-legacy.node.development.js:7061:10)
    at eval (C:/Users/camak/Documents/notlega.github.io/node_modules/.pnpm/@astrojs+react@2.2.1_@types+react-dom@18.2.4_@types+react@18.2.11_react-dom@18.2.0_react@18.2.0/node_modules/@astrojs/react/server.js:154:46)
    at new Promise (<anonymous>)
    at renderToStaticNodeStreamAsync (C:/Users/camak/Documents/notlega.github.io/node_modules/.pnpm/@astrojs+react@2.2.1_@types+react-dom@18.2.4_@types+react@18.2.11_react-dom@18.2.0_react@18.2.0/node_modules/@astrojs/react/server.js:153:9)
    at async Object.renderToStaticMarkup (C:/Users/camak/Documents/notlega.github.io/node_modules/.pnpm/@astrojs+react@2.2.1_@types+react-dom@18.2.4_@types+react@18.2.11_react-dom@18.2.0_react@18.2.0/node_modules/@astrojs/react/server.js:116:11)
    at async renderFrameworkComponent (C:/Users/camak/Documents/notlega.github.io/node_modules/.pnpm/astro@2.6.2/node_modules/astro/dist/runtime/server/render/component.js:187:26)
```

**Comment by notlega** [comment]
My bad, I fixed it
