### ISSUE TITLE
Typography issue not build the project compiled fail (bug)

### ISSUE THREAD

**Issue by rahul8864** [creativetimofficial/material-tailwind#496]
### I use my project material-tailwind but build comming like this issue:

Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (3/5)  [ ===]
RangeError: Maximum call stack size exceeded
    at P (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:279069)
    at l (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:274636)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275837
    at Array.forEach (<anonymous>)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275810
    at Array.forEach (<anonymous>)
    at a (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275630)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275894
    at Array.forEach (<anonymous>)
    at l (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275587)

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
RangeError: Maximum call stack size exceeded
    at P (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:279069)
    at l (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:274636)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275837
    at Array.forEach (<anonymous>)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275810
    at Array.forEach (<anonymous>)
    at a (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275630)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275894
    at Array.forEach (<anonymous>)
    at l (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275587)
RangeError: Maximum call stack size exceeded
    at P (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:279069)
    at l (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:274636)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275837
    at Array.forEach (<anonymous>)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275810
    at Array.forEach (<anonymous>)
    at a (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275630)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275894
    at Array.forEach (<anonymous>)
    at l (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275587)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error 
RangeError: Maximum call stack size exceeded
    at P (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:279069)
    at l (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:274636)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275837
    at Array.forEach (<anonymous>)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275810
    at Array.forEach (<anonymous>)
    at a (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275630)
    at C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chunks\227.js:5:275894
    at Array.forEach (<anonymous>)
    at l (C:\Users\admin\OneDrive\Desktop\nextjs\startnew\devmobilechas_material\.next\server\chun ✓ Generating static pages (5/5)

> Export encountered errors on following paths:
        /_not-found
        /page: /

### depandence
    "@material-tailwind/react": "^2.1.4",
    "next": "13.5.4",
    "react": "^18",
    "react-dom": "^18",

### I fix issue temporary "where where i use Typography commented" and build project it worked.

**Comment by rahul8864** [comment]
I got this problem issue fix only Come (Next.js App Router) again i try to (Next.js Page Router) is Working Fine 👍🏻
